default_platform(:ios)
platform :ios do
desc "Runniing all test"
  lane :run_test do
    scan(
    project:"MoviesApp.xcodeproj",
    scheme: "MoviesApp",
    output_directory: "Reports/Scan",
    clean: true,
    code_coverage: true,
    device: "iPhone 13 Pro Max",
    )
  end
end


